### ISSUE TITLE
títulos para artículos

### ISSUE THREAD

**Issue by ferskewes** [opensourcechile/constitucion_blog#11]
En la sección de línea de tiempo, sugeriría además de indicar el artículo, darle un nombre al artículo de que se trate (por ejemplo, en lugar de "artículo 7º", pondría: "artículo 7º: principio de legalidad". Lo anterior, pues me parece más sencillo explorar el sitio de esa manera que solo en función de los números de los artículos, especialmente para personas que no conocen la Constitución.

**Comment by eduramirezh** [comment]
Totalmente de acuerdo. Un feedback constante que he recibido es que faltan los "títulos de los artículos". No me gusta el "inventarle" títulos, pero creo que, como dices tú, es especialmente útil para gente que no conoce la Constitución, que es justamente la gente a la que queremos llegar.
De todas maneras, trataría de que los temas los llamemos de una forma corta, simple y lo más objetiva posible.

El conflicto que veo es que la numeración de los artículos ha cambiado, por lo que el artículo 83 de ahora habla de cosas diferentes que el artículo 83 del '89, por ejemplo.

Se me ocurren 2 cosas para solucionar esto:

 - Ahora estoy trabajando en una sección con los contenidos de la Constitución actual solamente, con un índice. Ahí podríamos poner estos títulos.
 - En el timeline, podríamos poner una breve descripción de cada ley. El "objetivo" de ese cambio.

¿Qué te parece?

Tengo también esta lista de temas que sugeriste antes. La podríamos usar de base, pero habría que agregar los artículos (actuales) que faltan:

 Capítulo I: Bases de la Institucionalidad

Artículo 1º: familia como núcleo fundamental de la sociedad; grupos intermedios.

Capítulo II: Nacionalidad y Ciudadanía

No veo mayores temas, quizás solo artículo 15 (voto voluntario).

Capítulo III: Derechos y Deberes Fundamentales

Este es el capítulo más sensible para la discusión actual. Hay que abordarlo completamente.

Artículo 19: Derechos fundamentales consagrados. Hay que abordar todos los numerales. Eventualmente podría agregarse una referencia a la manera en que hasta ahora han sido interpretados esos derechos.

Artículo 20: Recurso de protección. Cuáles son los derechos que se encuentran resguardados mediante el recurso de protección y cuáles no y por qué.

Artículo 21: Recurso de amparo.

Artículo 22: Deber de honrar a la patria y emblemas nacionales. Servicio militar obligatorio.

Artículo 23: Nuevamente grupos intermedios (esto viene de la ideología gremialista de Jaime Guzmán).

Capítulo IV: Gobierno

Artículo 25: Requisitos para ser Presidente, duración en el cargo.

Artículo 32: Atribuciones del Presidente de la República.

Artículos 39 a 45: Estados de excepción constitucional.

Capítulo IV: Congreso Nacional

Artículo 46: Congreso bicameral (dado que hay propuestas de Congreso unicameral).

Artículos 48, 50 y 57: Requisitos para ser diputado y senador.

Artículo 51: Reemplazo de parlamentarios.

Artículos 52, 53 y 54: Atribuciones de la Cámara de Diputados, del Senado y del Congreso.

Artículo 63: Materias de ley.

Artículo 64: Norma que permite dictar “decretos con fuerza de ley” (así es como se regulaba en dictadura)

Artículo 65: Formación de la ley, materias de iniciativa exclusiva del Presidente.

Artículo 67: Reglas sobre la ley de presupuestos (límites del Congreso).

Artículo 74: Urgencias (decisión del Presidente).

Capítulo VIII: Tribunal Constitucional.

Artículo 92: Integración.

Artículo 93: Atribuciones (entre ellas, control preventivo de constitucionalidad)

Capítulo X: Contraloría General de la República

Artículos 98 y 99: Atribuciones.

Capítulo XI: Fuerzas Armadas, de Orden y de Seguridad

Creo que las disposiciones a nivel constitucional son bastante estándar.

Capítulo XII: Consejo de Seguridad Nacional (COSENA)

Artículos 106 y 107: Integración y atribuciones.

Capítulo XIV: Gobierno y administración interior del Estado.

Estos temas fueron recientemente reformados (2017) y es bastante enredado porque aún no entra completamente en vigencia, quizás se puede hacer un paralelo con cómo estaban regulados y cómo quedó ahora.

Capítulo XV: Reforma de la Constitución.

Disposiciones transitorias.

Artículo tercero: minería del cobre.

Artículo séptimo: indulto delitos anteriores a 1990.

**Comment by ferskewes** [comment]
Estoy de acuerdo con lo que propones. Voy a revisar los títulos que le puse a los artículos y complementar aquellos que faltan. ¿Lo escribo directamente acá o hago otra cosa? Sorry por lo noob.

**Comment by eduramirezh** [comment]
Bacán. Escríbelo acá no más mejor, para que tengamos un registro de la conversación sobre este punto. Gracias!!

**Comment by ferskewes** [comment]
Capítulo I: Bases de la Institucionalidad

Artículo 1º: Dignidad humana - familia - grupos intermedios - principio de servicialidad - deberes del Estado.

Artículo 2º: Emblemas nacionales.

Artículo 3º: Organización del Estado.

Artículo 4º: Forma de gobierno.

Artículo 5º: Soberanía.

Artículo 6º: Principio de legalidad.

Artículo 7º: Principio de juridicidad.

Artículo 8º: Principio de probidad - Principio de publicidad.

Artículo 9º: Proscripción del terrorismo.

Capítulo II: Nacionalidad y Ciudadanía

Artículo 10: Adquisición de nacionalidad chilena.

Artículo 11: Pérdida de nacionalidad chilena.

Articulo 12: Amparo por privación o desconocimiento de la nacionalidad chilena.

Artículo 13: Ciudadanía.

Artículo 14: Derechos políticos para extranjeros.

Artículo 15: Voto personal, igualitario, secreto y voluntario - Plebiscitos.

Artículo 16: Suspensión del derecho de sufragio.

Artículo 17: Pérdida de la calidad de ciudadano.

Artículo 18: Sistema electoral.

Capítulo III: Derechos y Deberes Fundamentales

Artículo 19: Derechos fundamentales consagrados. 

Numeral 1: Derecho a la vida e integridad física - Protección de la vida del nasciturus.

Numeral 2: Derecho a la igualdad ante la ley - Proscripción de la arbitrariedad.

Numeral 3: Derecho a la igual protección de la ley en el ejercicio de los derechos - Debido proceso.

Numeral 4: Derecho a la vida privada y honra.

Numeral 5: Derecho a la inviolabilidad del hogar y comunicaciones privadas.

Numeral 6: Libertad de conciencia. Exenciones a las iglesias.

Numeral 7: Libertad personal y seguridad individual.

Numeral 8: Derecho a vivir en un medio ambiente libre de contaminación.

Numeral 9: Derecho a la protección a la salud.

Numeral 10: Derecho a la educación.

Numeral 11: Libertad de enseñanza.

Numeral 12: Libertad de emitir opinión e informar sin censura previa - Consejo Nacional de Televisión como órgano constitucionalmente autónomo.

Numeral 13: Derecho de reunión.

Numeral 14: Derecho de petición.

Numeral 15: Derecho de asociación.

Numeral 16: Libertad de trabajo. Derecho a la negociación colectiva.

Numeral 17: Admisión a funciones y empleos públicos.

Numeral 18: Derecho a la seguridad social.

Numeral 19: Derecho a sindicarse.

Numeral 20: Igual repartición de los tributos y cargas públicas.

Numeral 21: Derecho a desarrollar cualquier actividad económica - Principio de subsidariedad.

Numeral 22: No discriminación arbitraria en el trato en materia económica.

Numeral 23: Libertad para adquirir el dominio.

Numeral 24: Derecho de propiedad - Dominio estatal sobre las minas - Concesiones mineras y dominio sobre las mismas - Propiedad sobre los derechos de aguas.

Numeral 25: Libertad de crear y difundir las artes. Derecho de autor. 

Numeral 26: Núcleo esencial de los derechos fundamentales.
 
Artículo 20: Recurso de protección. Derechos que resguarda.

Artículo 21: Recurso de amparo.

Artículo 22: Deber de honrar a la patria y emblemas nacionales - Servicio militar obligatorio.

Artículo 23: Grupos intermedios.

Capítulo IV: Gobierno

Artículo 24: Presidente de la República, jefe de Estado.

Artículo 25: Requisitos para ser Presidente, duración en el cargo.

Artículo 26: Elección del Presidente.

Artículo 27: Calificación de la elección presidencial.

Artículo 28: Subrogancias del Presidente por impedimento para tomar posesión en el cargo.

Artículo 29: Subrogancias del Presidente por impedimento temporal.

Artículo 30: Cesación en el cargo de Presidente.

Artículo 31: Atribuciones del Presidente designado por el Congreso Pleno o del Vicepresidente de la República.

Artículo 32: Atribuciones del Presidente de la República.

Artículo 33: Ministros de Estado.

Artículo 34: Requisitos para ser Ministro. Reemplazo.

Artículo 36: Responsabilidad de los Ministros.

Artículo 37: Asistencia de Ministros a sesiones del Congreso.

Artículo 37 bis: Incompatibilidades y prohibiciones de los Ministros.

Artículo 38: Bases generales de la Administración del Estado.

Artículos 39: Estados de excepción constitucional.

Artículo 40: Estado de asamblea - Estado de sitio.

Artículo 41: Estado de catástrofe.

Artículo 42: Estado de emergencia.

Artículo 43: Suspensión de derechos constitucionales durante estados de excepción.

Artículo 44: Regulación por ley orgánica constitucional de los estados de excepción.

Artículo 45: Atribuciones de los tribunales de justicia durante los estados de excepción.

Capítulo IV: Congreso Nacional

Artículo 46: Congreso bicameral.

Artículo 47: Composición Cámara de Diputados.

Artículo 48: Requisitos para ser Diputado.

Artículo 49: Composición del Senado.

Artículo 50 y 57: Requisitos para ser Senador.

Artículo 51: Elecciones y reemplazo de parlamentarios.

Artículos 52: Atribuciones de la Cámara de Diputados.

Artículo 53: Atribuciones del Senado.

Artículo 54: Atribuciones del Congreso.

Artículo 55: Instalación del Congreso - Acusaciones constitucionales.

Artículo 56: Quórum para sesionar.

Artículo 56 bis: Cuenta pública del Congreso.

Artículo 57: Inhabilidades para ser parlamentario.

Artículo 58: Incompatibilidades de los cargos parlamentarios.

Artículo 59: Excepciones a incompatibilidades parlamentarias en caso de guerra.

Artículo 60: Causales de cesación en el cargo parlamentario.

Artículo 61: Fuero parlamentario.

Artículo 62: Dieta parlamentaria.

Artículo 63: Materias de ley.

Artículo 64: Norma que permite dictar “decretos con fuerza de ley”.

Artículo 65: Formación de la ley - Materias de iniciativa exclusiva del Presidente.

Artículo 66: Leyes de quórum calificado.

Artículo 67: Reglas sobre la ley de presupuestos.

Artículo 68: Plazo para volver a presenta proyectos rechazados.

Artículo 69: Adiciones o correcciones a proyectos de ley.

Artículo 70: Comisión mixta para proyectos rechazados.

Artículo 71: Comisión mixta para proyectos con adiciones y correcciones.

Artículo 72: Promulgación de la ley.

Artículo 73: Veto del Presidente de la República.

Artículo 74: Urgencias.

Artículo 75: Promulgación en caso de silencio del Presidente.

Capítulo VI: Poder Judicial.

Artículo 76: Principio de plenitud jurisdiccional - Principio de inexcusabilidad - Principio de independencia - Principio de Imperio

Artículo 77: Regulación de la organización y atribuciones de los tribunales por ley orgánica constitucional. 

Artículo 78: Nombramiento jueces.

Artículo 79: Responsabilidad funcionaria o ministerial de los jueces.

Artículo 80: Principio de inamovilidad.

Artículo 81: Fuero jueves.

Artículo 82: Superintendencia directiva, correccional y económica por parte de la Corte Suprema.
 
Capítulo VII: Ministerio Publico:

Artículo 83: Atribuciones del Ministerio Público.

Artículo 84: Regulación del Ministerio Público por ley orgánica constitucional.
 
Artículo 85: Fiscal Nacional.
 
Artículo 86: Fiscales Regionales.
 
Artículo 87: Nombramiento Fiscales Regionales.
 
Artículo 88: Fiscales Adjuntos.

Artículo 89: Remoción fiscales.

Artículo 90: Fuero fiscales.

Artículo 91: Superintendencia directiva, correccional y económica por parte del Fiscal Nacional.

Capítulo VIII: Tribunal Constitucional.

Artículo 92: Integración del Tribunal Constitucional.

Artículo 93: Atribuciones del Tribunal Constitucional.

Artículo 94: Impugnación decisiones del Tribunal Constitucional.

Capítulo IX: Servicio Electoral y Justicia Electoral.

Artículo 94 bis: Servicio Electoral.

Artículo 95: Tribunal Calificador de Elecciones.

Artículo 96: Tribunales Electorales Regionales.

Artículo 97: Financiamiento Justicia Electoral.

Capítulo X: Contraloría General de la República

Artículo 98: Atribuciones Contraloría - Control de legalidad - Facultades fiscalizadoras - Requisitos para ser Contralor.

Artículo 99: Toma de razón - Organización de Contraloría mediante ley orgánica constitucional.

Artículo 100: Autorización para pagos por Tesorerías del Estado.

Capítulo XI: Fuerzas Armadas, de Orden y de Seguridad

Artículo 101: Composición y dependiencia de  Fuerzas Armadas y de Fuerzas de Orden y Seguridad Pública - Principios de obedencia, no deliberancia y jerarquía.

Artículo 102: Incorporación a Fuerzas Armadas y de Carabineros.

Artículo 103: Control de armas.

Artículo 104: Comandantes de Fuerzas Armadas y Carabineros.

Artículo 105: Nombramientos, ascensos y retiros de los oficiales de las Fuerzas Armadas, de Orden y de Seguridad.

Capítulo XII: Consejo de Seguridad Nacional

Artículo 106: Integración y atribuciones del COSENA.

Artículo 107: Sesiones, acuerdos y funcionamiento del COSENA.

Capítulo XIII: Banco Central.

Artículo 108: Autonomía del Banco Central.

Artículo 109: Atribuciones del Banco Central.

Capítulo XIV: Gobierno y administración interior del Estado.

Artículo 110: División del territorio de la República.

Artículo 111: Gobierno Regional.

Artículo 112: Norma derogada.

Artículo 113:  Consejo Regional.

Artículo 114: Transferencias a gobiernos regionales.

Artículo 115: Principio de desarrollo territorial armónico y equitativo.

Artículo 115 bis: Delegación presidencial regional.

Artículo 116: Delegación presidencial provincial.

Artículo 117: Encargados de delegados presidenciales provinciales.

Artículo 118: Administración comunal - Municipalidades - Alcaldes.

Artículo 119: Concejo Municipal.

Artículo 120: Instalación y fusión de municipalidades.

Artículo 121: Facultades de municipalidades en materia de empleo y organización interna.

Artículo 122: Autonomía municipal en la administración de sus finanzas.

Artículo 123: Coordinación municipalidades - Areas metropolitanas.

Artículos 124: Requisitos, incompatibilidades y prohibiciones para cargos de la administración comunal, provincial y regional.

Artículos 125: Causales de cesación en el cargo de gobernador regional, de alcalde, consejero regional y concejal.

Artículo 126: Cuestiones de competencia.

Artículo 126 bis: Territorios especiales.

Capítulo XV: Reforma de la Constitución.

Artículo 127: Inicio proyectos de reforma constitucional - Quórums de aprobación.

Artículo 128: Procedimiento para proyectos de reforma constitucional una vez aprobados por las Cámaras.

Artículo 129: Convocatoria a plebiscito.

Disposiciones transitorias.

Artículo primero: ultraactividad disposiciones previas a la Constitución.

Artículo segundo: ultraactividad reglas previas a Código de Minería.

Artículo tercero: ultraactividad reglas aplicables a la gran minería del cobre.

Artículo cuarto: Vigencia leyes materias que de leyes orgánicas constitucionales o aprobadas con quórum calificado.

Artículo quinto: Vigencia leyes que regulen materias no comprendidas en reserva de ley.

Artículo sexto: Vigencia leyes de afectación tributos a destino determinado.

Artículo séptimo: Indulto delitos anteriores a 1990.

Artículo octavo: Vigencia normas Ministerio Público.

Artículo noveno: Reglas para primer nombramiento de ciertos cargos.

Artículo décimo: Entrada en vigencia normas sobre atribuciones de municipalidades.

Artículo décimo primero: Inhabilidades para integrar Corte Suprema tras reforma constitucional.

Artículo décimo segundo: Mandato presidencial de seis años sin reelección.

Artículo décimo tercero: Integración del Senado - Modificaciones a la Ley Orgánica Constitucional sobre Votaciones Populares y Escrutinios que digan relación con el número de senadores y diputados,.

Artículo décimo cuarto: Reemplazo de los entonces actuales Ministros y nombramiento de los nuevos integrantes del Tribunal Constitucional.

Artículo décimo quinto: Tratados internacionales aprobados por el Congreso Nacional con anterioridad a la entrada en vigor de la reforma constitucional.

Artículo décimo sexto: Vigencia reformas introducidas al Capítulo VIII.

Artículo décimo séptimo: Regla sobre dependencia de as Fuerzas de Orden y Seguridad Pública previo a creación del Ministerio de Seguridad Publica.

Artículo décimo octavo: Entrada en vigencia modificaciones dispuestas en el artículo 57, Nº 2.

Artículo décimo noveno: Suspensión del derecho de sufragio de las personas procesadas por hechos anteriores al 16 de Junio de 2005.

Artículo vigésimo: Reclamaciones por la conducta ética de los profesionales que no pertenezcan a colegios profesionales.

Artículo vigésimo primero: Vigencia reforma introducida en el numeral 10º del artículo 19.

Artículo vigésimo segundo: Vigencia de estatutos especiales a que se refiere el artículo 126 bis.

Artículo vigésimo tercero: Vigencia reformas introducidas a los artículos 15 y 18 sobre voluntariedad del voto e incorporación al registro electoral.

Artículo vigésimo cuarto: Reconocimiento jurisdicción Corte Penal Internacional.

Artículo vigésimo quinto: Entrada en vigencia de modificación introducida en el inciso cuarto del artículo 60.

**Comment by dsilvaschorr** [comment]
Hola! Me parece que ponerle nombres a los artículos puede dar pie a pérdida de objetividad. Quizás como alternativa podamos indicar al capítulo que pertenecen los artículos y así la gente se puede orientar mejor que viendo el número del artículo. 
Se me ocurre que en cada capítulo se indique un porcentaje de cuánto del capitulo ha sido modificado desde el inicio de la constitución hasta la fecha. Así se hace más amigable también.

**Comment by dsilvaschorr** [comment]
Algo así:

Capítulo I: Bases de la Institucionalidad

Artículos 1 a 9.

Capítulo II: Nacionalidad y Ciudadanía

Artículos 10 a 18.

Capítulo III: Derechos y Deberes Fundamentales

Artículos 19 a 23.

Capítulo IV: Gobierno

Artículo 24 a 45.

Capítulo IV: Congreso Nacional

Artículos 46 a 75.

Capítulo VI: Poder Judicial.

Artículos 76 a 82.

Capítulo VII: Ministerio Publico:

Artículos 83 a 91.

Capítulo VIII: Tribunal Constitucional.

Artículos 92 a 94.

Capítulo IX: Servicio Electoral y Justicia Electoral.

Artículos 94 a 97.

Capítulo X: Contraloría General de la República

Artículos 98 a 100.

Capítulo XI: Fuerzas Armadas, de Orden y de Seguridad

Artículos 101 a 105.

Capítulo XII: Consejo de Seguridad Nacional

Artículos 106 a 107.

Capítulo XIII: Banco Central.

Artículos 108 a 109.

Capítulo XIV: Gobierno y administración interior del Estado.

Artículos 110 a 126.

Capítulo XV: Reforma de la Constitución.

Artículos 127 a 129.

Disposiciones transitorias.

Artículos 1 a 25.

**Comment by eduramirezh** [comment]
Ya estoy haciendo el trabajo de poner etiquetas por artículo, y también ha sido un comentario de los usuarios que se ha repetido mucho. Qué te parece @dsilvaschorr  si ponemos etiquetas por artículos por ahora, vemos que tan útiles y/o pólemicas son y las vamos mejorando en base a eso?

**Comment by eduramirezh** [comment]
Va avanzando la cosa https://github.com/opensourcechile/constitucion/commit/dc7010c13d0cb2a995dbb0eecfaaf342f9c50191 vamos a poder usar este mismo archivo para después agregar por ejemplo los links correspondientes al repertorio de jurisprudencia

**Comment by eduramirezh** [comment]
@ferskewes ojo que faltan las 3 últimas disposiciones transitorias, las voy a dejar sin temas por mientras

**Comment by eduramirezh** [comment]
Cerrado con https://github.com/opensourcechile/constitucion/pull/23
