### ISSUE TITLE
Definición de inciso

### ISSUE THREAD

**Issue by ferskewes** [opensourcechile/constitucion_blog#12]
En la parte de Glosario, respecto a la definición de inciso me parece que sería mejor señalar que son los distintos párrafos de un artículo, separados por un punto aparte. Ello, pues no puede haber un inciso "fuera" de un artículo. Me parece más sencillo de comprender si se señala que, en el fondo, inciso es igual = párrafo en jerga legal.

**Comment by eduramirezh** [comment]
Gracias @ferskewes! Dado que tú tienes más experiencia en esta área, podrías hacer un Pull Request tú directamente con estos cambios? Tienes que:

1. Editar el archivo glosario.md con los cambios que sugieres (aquí un link directo https://github.com/opensourcechile/constitucion/edit/gh-pages/glosario.md)
2. Ponerle un título al PR (ej: Hacer más precisa la definición de inciso)
3. Seleccionar la opción (si es que te aparece, quizás no te deja otra alternativa) que dice: Create a new branch for this commit and start a pull request.

Eso es todo. Después lo miro para ver que este todo ok y lo incorporo y publico. Cualquier cosa me puedes preguntar directamente

**Comment by ferskewes** [comment]
Ok, lo intenté, a ver si lo logré...

**Comment by eduramirezh** [comment]
#13
