### ISSUE TITLE
Error en enlace hacia atrás desde Ley 18825

### ISSUE THREAD

**Issue by moniquelyse** [opensourcechile/constitucion_blog#16]
En la página de la [Ley 18825](http://leyabierta.cl/1989/08/17/LEY_18825.html), el enlace que lleva atrás, al Decreto ley nº 3.464, da 404.

El link actualmente es: http://leyabierta.cl/1980/08/08/DECRETO_LEY_No_3.464.html y debería ser http://leyabierta.cl/1980/08/08/DECRETO_LEY_Nº_3.464.html
(la diferencia es un caracter "o" en vez de "º").

**Comment by eduramirezh** [comment]
Muchas gracias por reportar esto, y darte el tiempo de ver cuál era la causa!. Esto queda arreglado con los commits: https://github.com/opensourcechile/constitucion/commit/d843c23cdab5f09842465fc7de4c290924c52e77 y https://github.com/opensourcechile/constitucion/commit/114b3385998c6522082de17d61b8e9de7b18240c 
Puedes ver que funciona acá https://leyabierta.cl/1989/08/17/LEY18825.html
