### ISSUE TITLE
Mejorar formato de fechas

### ISSUE THREAD

**Issue by eduramirezh** [opensourcechile/constitucion_blog#17]
En el timeline, cambiar formato de fechas de 08/1980 a "1 de Agosto de 1980"

**Comment by tlarrain** [comment]
@eduramirezh traté de pushear al repositorio pero me dio 403, me faltará algún permiso?
`remote: Permission to opensourcechile/constitucion.git denied to tlarrain.`

**Comment by eduramirezh** [comment]
Bacán! Sí, tienes que crear un Pull request. Por el momento prefiero revisar todos los PR yo antes de mergearlos, porque igual hay cosas que se pueden quebrar

**Comment by tlarrain** [comment]
no puedo subir mi branch al repositorio para hacer el pull request. No estoy pusheando a las ramas existentes ni nada, solamente a una nueva para generar el PR. Puedes revisar que tenga permisos para pushear ramas?

**Comment by eduramirezh** [comment]
Ahora sí, no tenías acceso de write pero ya te agregué. La alternativa habría sido hacer un fork tuyo de este repo y crear el pull request desde ahí

**Comment by eduramirezh** [comment]
Confírmame si te funciona please

**Comment by tlarrain** [comment]
listo, creado el Pull Request #18

**Comment by eduramirezh** [comment]
Bacán!
