### ISSUE TITLE
Definiciones Glosario

### ISSUE THREAD

**Issue by dsilvaschorr** [opensourcechile/constitucion_blog#27]
Hola! Para el glosario sugiero agregar este concepto:

"Grupos intermedios: organizaciones voluntariamente creadas por la persona humana, ubicadas entre el individuo y el estado, para que cumplan con sus fines específicos a través de los medios de que dispongan, con autonomía frente al aparato publico."

La definición es de José Luis Cea, está en un "Glosario" que mantenía disponible para sus alumnos. Me imagino que la cita correcta sería indicar que es un apunte de clases.

**Comment by eduramirezh** [comment]
Me parece muy bien! Sería bacán si haces un Pull Request tú con este cambio para que sepas como hacerlo en el futuro. @ferskewes te puede dar testimonio de que no es tan pelúo
https://github.com/opensourcechile/constitucion/issues/12#issuecomment-558346736

**Comment by eduramirezh** [comment]
Agregado en https://github.com/opensourcechile/constitucion/pull/28
