### ISSUE TITLE
agregar título de últimas 3 disposiciones transitorias

### ISSUE THREAD

**Issue by ferskewes** [opensourcechile/constitucion_blog#31]
Vigésimo sexta: Normas para implementación de reformas sobre consejeros regionales.

Vigésimo séptima: Normas para implementación de reformas a directivos del Servicio Electoral.

Vigésimo octava: Normas para primera elección por sufragio universal en votación directa de los gobernadores regionales.

**Comment by eduramirezh** [comment]
@ferskewes puedes crear un PR (como la vez anterior) donde agregas eso en este archivo: https://github.com/opensourcechile/constitucion/blob/gh-pages/_data/estructura.yml. Guíate en como se definen los temas en los otros artículos y listo

**Comment by paullorb** [comment]
Hola! Este issue se podría cerrar no?
